spring.application.name=java-mail

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=darshanlakadecdac@gmail.com
spring.mail.password=ajsyuwehyuonnsse
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
