spring.application.name=java-mail

spring.mail.host=smtp.gmail.com
spring.mail.port=
spring.mail.username=your mail
spring.mail.password=your smtp key
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
